In [2]:
x <- matrix(nrow=4, ncol=3, data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [3]:
rownames(x) <- c("r1","r2","r3","r4")
x

colnames(x) <- c("c1","c2","c3")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [4]:
x <- matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [5]:
d <- diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [6]:
d <- diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [7]:
x <- matrix(nrow=4, ncol=2, data=1:8, byrow=TRUE)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [8]:
xt <- t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [9]:
x <- matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

rowSums(x)

colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

In [10]:
x <- matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

rowMeans(x)

colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

In [11]:
x <- matrix(c(1,2,3,4), nrow=2)
y <- matrix(c(5,6,7,8), nrow=2)

x + y

     [,1] [,2]
[1,] 6    10
[2,] 8    12

In [12]:
x <- matrix(c(5,6,7,8), nrow=2)
y <- matrix(c(1,2,3,4), nrow=2)

x - y

     [,1] [,2]
[1,] 4    4
[2,] 4    4

In [13]:
x <- matrix(c(1,2,3,4), nrow=2)
y <- matrix(c(5,6,7,8), nrow=2)

x * y

     [,1] [,2]
[1,]  5   21
[2,] 12   32

In [14]:
x <- matrix(c(10,20,30,40), nrow=2)
y <- matrix(c(2,4,5,8), nrow=2)

x / y

     [,1] [,2]
[1,] 5    6
[2,] 5    5

In [15]:
x <- matrix(c(1,2,3,4), nrow=2)
y <- matrix(c(5,6,7,8), nrow=2)

x %*% y

     [,1] [,2]
[1,] 23   31
[2,] 34   46

In [16]:
x <- matrix(c(1,2,3,4), nrow=2)

det(x)

[1] -2

In [17]:
x <- matrix(c(1,2,3,4), nrow=2)

solve(x)

     [,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [18]:
x <- matrix(c(4,2,2,3), nrow=2)

eigen(x)

eigen() decomposition
$values
[1] 5.561553 1.438447

$vectors
           [,1]       [,2]
[1,] -0.7882054  0.6154122
[2,] -0.6154122 -0.7882054

In [19]:
x <- matrix(1:9, nrow=3)

x

t(x)

rowSums(x)

colSums(x)

rowMeans(x)

colMeans(x)

det(matrix(c(1,2,3,4),2))

solve(matrix(c(1,2,3,4),2))

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6
[3,] 7    8    9

[1] 12 15 18

[1]  6 15 24

[1] 4 5 6

[1] 2 5 8

[1] -2

     [,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5