In [40]:
x <- matrix(nrow = 4, ncol = 3, data = c(1:12))
x

rownames(x) <- c("r1", "r2", "r3", "r4")
x

colnames(x) <- c("c1", "c2", "c3")
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [41]:
x <- matrix(nrow = 4, ncol = 2, data = 2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [42]:
d <- diag(1, nrow = 3, ncol = 3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [43]:
d <- diag(5, nrow = 3, ncol = 3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [44]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [45]:
xt <- t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [46]:
x <- matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

rowSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

In [47]:
x <- matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 10 26

In [48]:
x <- matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

rowMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

In [29]:
exp(1)

exp(2)

exp(3)

[1] 2.718282

[1] 7.389056

[1] 20.08554

In [30]:
log(10)

log(exp(1))

log(100)

[1] 2.302585

[1] 1

[1] 4.60517

In [31]:
log10(10)

log10(100)

log10(1000)

[1] 1

[1] 2

[1] 3

In [32]:
sin(pi/2)

cos(0)

tan(pi/4)

[1] 1

[1] 1

[1] 1

In [33]:
round(2.3456)

round(2.3456,2)

ceiling(2.1)

floor(2.9)

trunc(2.9)

[1] 2

[1] 2.35

[1] 3

[1] 2

[1] 2

In [34]:
max(c(2,5,8,3))

min(c(2,5,8,3))

[1] 8

[1] 2

In [35]:
sum(c(2,3,5,7))

prod(c(2,3,5))

[1] 17

[1] 30

In [36]:
mean(c(2,3,5,7))

[1] 4.25

In [37]:
1:10

seq(1,10)

seq(1,10,by=2)

seq(0,1,length=5)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

[1] 1 3 5 7 9

[1] 0.00 0.25 0.50 0.75 1.00

In [38]:
rep(5,4)

rep(c(1,2),3)

rep(c(1,2),each=3)

[1] 5 5 5 5

[1] 1 2 1 2 1 2

[1] 1 1 1 2 2 2

In [39]:
x <- c(2,3,5,7)

x^2

sqrt(x)

log(x)

exp(x)

sum(x)

prod(x)

mean(x)

max(x)

min(x)

round(pi,3)

rep(x,2)

seq(1,20,by=2)

[1]  4  9 25 49

[1] 1.414214 1.732051 2.236068 2.645751

[1] 0.6931472 1.0986123 1.6094379 1.9459101

[1]    7.389056   20.085537  148.413159 1096.633158

[1] 17

[1] 210

[1] 4.25

[1] 7

[1] 2

[1] 3.142

[1] 2 3 5 7 2 3 5 7

 [1]  1  3  5  7  9 11 13 15 17 19